import logging

import pandas as pd

from sqlalchemy import Engine, create_engine, select
from sqlalchemy.orm import Session

from etl.models import (
    ActivityArea,
    ActivitySubarea,
    Base,
    Cnae,
    LegalNature,
    Municipality,
    Organization,
    OrganizationArea,
    OrganizationCnae,
    OrganizationSubarea,
)


# Source columns and their database names.
AREA_COLUMNS = {
    "Area_Assistencia_social": "Assistência social",
    "Area_Associacoes_patronais_e_profissionais": (
        "Associações patronais e profissionais"
    ),
    "Area_Cultura_e_recreacao": "Cultura e recreação",
    "Area_Desenvolvimento_e_defesa_de_direitos_e_interesses": (
        "Desenvolvimento e defesa de direitos e interesses"
    ),
    "Area_Educacao_e_pesquisa": "Educação e pesquisa",
    "Area_Outras_atividades_associativas": (
        "Outras atividades associativas"
    ),
    "Area_Religiao": "Religião",
    "Area_Saude": "Saúde",
}


SUBAREA_COLUMNS = {
    "SubArea_Assistencia_social": (
        "Assistência social",
        "Assistência social",
    ),
    "SubArea_Associacoes_de_atividades_nao_especificadas_anteriormente": (
        "Associações de atividades não especificadas anteriormente",
        "Associações patronais e profissionais",
    ),
    "SubArea_Associacoes_de_produtores_rurais_pescadores_e_similares": (
        "Associações de produtores rurais, pescadores e similares",
        "Associações patronais e profissionais",
    ),
    "SubArea_Associacoes_empresariais_e_patronais": (
        "Associações empresariais e patronais",
        "Associações patronais e profissionais",
    ),
    "SubArea_Associacoes_profissionais": (
        "Associações profissionais",
        "Associações patronais e profissionais",
    ),
    "SubArea_Atividades_de_apoio_a_educacao": (
        "Atividades de apoio à educação",
        "Educação e pesquisa",
    ),
    "SubArea_Cultura_e_arte": (
        "Cultura e arte",
        "Cultura e recreação",
    ),
    "SubArea_Desenvolvimento_e_defesa_de_direitos": (
        "Desenvolvimento e defesa de direitos",
        "Desenvolvimento e defesa de direitos e interesses",
    ),
    "SubArea_Educacao_infantil": (
        "Educação infantil",
        "Educação e pesquisa",
    ),
    "SubArea_Educacao_profissional": (
        "Educação profissional",
        "Educação e pesquisa",
    ),
    "SubArea_Ensino_fundamental": (
        "Ensino fundamental",
        "Educação e pesquisa",
    ),
    "SubArea_Ensino_superior": (
        "Ensino superior",
        "Educação e pesquisa",
    ),
    "SubArea_Esportes_e_recreacao": (
        "Esportes e recreação",
        "Cultura e recreação",
    ),
    "SubArea_Estudos_e_pesquisas": (
        "Estudos e pesquisas",
        "Educação e pesquisa",
    ),
    "SubArea_Hospitais": (
        "Hospitais",
        "Saúde",
    ),
    "SubArea_Outras_formas_de_educacao_ensino": (
        "Outras formas de educação e ensino",
        "Educação e pesquisa",
    ),
    "SubArea_Outros_servicos_de_saude": (
        "Outros serviços de saúde",
        "Saúde",
    ),
    "SubArea_Religiao": (
        "Religião",
        "Religião",
    ),
}


def create_database_engine(db_url: str) -> Engine:
    """
    Creates a SQLAlchemy engine for PostgreSQL.
    """
    return create_engine(
        db_url,
        pool_pre_ping=True,
    )


def create_tables(engine: Engine) -> None:
    """
    Creates all tables defined in the SQLAlchemy models.
    """
    Base.metadata.create_all(engine)

    logging.info("Database tables created successfully.")


def load_dataframe(
    df: pd.DataFrame,
    engine: Engine,
) -> None:
    """
    Loads transformed data into PostgreSQL.
    """

    with Session(engine) as session:
        try:
            _load_legal_natures(df, session)
            _load_municipalities(df, session)
            _load_cnaes(df, session)
            _load_activity_areas(df, session)
            _load_activity_subareas(df, session)
            _load_organizations(df, session)

            # Organization IDs are generated by PostgreSQL.
            # Flush makes them available before creating relationships.
            session.flush()

            _load_organization_cnaes(df, session)
            _load_organization_areas(df, session)
            _load_organization_subareas(df, session)

            session.commit()

        except Exception:
            session.rollback()
            raise

    logging.info(
        "Data loaded successfully: %d organizations.",
        len(df),
    )


def _load_legal_natures(
    df: pd.DataFrame,
    session: Session,
) -> None:
    """
    Loads legal nature reference data.
    """

    legal_natures = (
        df[
            ["natureza_juridica"]
        ]
        .dropna()
        .drop_duplicates()
    )

    for row in legal_natures.itertuples(index=False):
        code = int(row.natureza_juridica)

        existing = session.get(
            LegalNature,
            code,
        )

        if existing is None:
            session.add(
                LegalNature(
                    code=code,
                    # TODO: replace with official legal nature name.
                    name=f"Natureza jurídica {code}",
                )
            )


def _load_municipalities(
    df: pd.DataFrame,
    session: Session,
) -> None:
    """
    Loads municipality reference data.
    """

    municipalities = (
        df[
            [
                "cd_municipio",
                "municipio_nome",
                "UF_Sigla",
            ]
        ]
        .dropna(subset=["cd_municipio"])
        .drop_duplicates(subset=["cd_municipio"])
    )

    for row in municipalities.itertuples(index=False):
        code = int(row.cd_municipio)

        existing = session.get(
            Municipality,
            code,
        )

        if existing is None:
            session.add(
                Municipality(
                    code=code,
                    name=(
                        str(row.municipio_nome)
                        if pd.notna(row.municipio_nome)
                        else None
                    ),
                    uf=(
                        str(row.UF_Sigla)
                        if pd.notna(row.UF_Sigla)
                        else None
                    ),
                )
            )


def _load_cnaes(
    df: pd.DataFrame,
    session: Session,
) -> None:
    """
    Loads CNAE reference data.

    The source dataset provides CNAE codes but does not
    provide their official names.
    """

    cnae_codes: set[str] = set()

    if "cnae" in df.columns:
        primary_cnaes = (
            df["cnae"]
            .dropna()
            .astype(str)
            .str.strip()
        )

        cnae_codes.update(
            code
            for code in primary_cnaes
            if code
        )

    if "cnae_secundaria" in df.columns:
        for value in df["cnae_secundaria"].dropna():
            for code in str(value).split("|"):
                code = code.strip()

                if code:
                    cnae_codes.add(code)

    if not cnae_codes:
        return

    existing_codes = set(
        session.scalars(
            select(Cnae.code)
        ).all()
    )

    new_codes = cnae_codes - existing_codes

    for code in sorted(new_codes):
        session.add(
            Cnae(
                code=code,
                name=None,
            )
        )


def _load_activity_areas(
    df: pd.DataFrame,
    session: Session,
) -> None:
    """
    Loads activity areas.
    """

    existing_areas = {
        area.name: area.id
        for area in session.scalars(
            select(ActivityArea)
        ).all()
    }

    next_id = max(existing_areas.values(), default=0) + 1

    for name in AREA_COLUMNS.values():
        if name in existing_areas:
            continue

        session.add(
            ActivityArea(
                id=next_id,
                name=name,
            )
        )

        existing_areas[name] = next_id
        next_id += 1


def _load_activity_subareas(
    df: pd.DataFrame,
    session: Session,
) -> None:
    """
    Loads activity subareas and associates each subarea
    with its parent activity area.
    """

    areas = {
        area.name: area.id
        for area in session.scalars(
            select(ActivityArea)
        ).all()
    }

    existing_subareas = {
        (subarea.area_id, subarea.name): subarea.id
        for subarea in session.scalars(
            select(ActivitySubarea)
        ).all()
    }

    next_id = max(
        (
            subarea.id
            for subarea in session.scalars(
                select(ActivitySubarea)
            ).all()
        ),
        default=0,
    ) + 1

    for column, (name, area_name) in SUBAREA_COLUMNS.items():
        area_id = areas[area_name]

        key = (area_id, name)

        if key in existing_subareas:
            continue

        session.add(
            ActivitySubarea(
                id=next_id,
                area_id=area_id,
                name=name,
            )
        )

        existing_subareas[key] = next_id
        next_id += 1


def _load_organizations(
    df: pd.DataFrame,
    session: Session,
) -> None:
    """
    Loads organizations into PostgreSQL.
    """

    for _, row in df.iterrows():
        organization = Organization(
            cnpj=str(row["cnpj"]),
            legal_name=(
                str(row["tx_razao_social_osc"])
                if pd.notna(row["tx_razao_social_osc"])
                else None
            ),
            trade_name=(
                str(row["tx_nome_fantasia_osc"])
                if pd.notna(row["tx_nome_fantasia_osc"])
                else None
            ),
            legal_nature_code=(
                int(row["natureza_juridica"])
                if pd.notna(row["natureza_juridica"])
                else None
            ),
            matrix_or_branch=(
                str(row["matriz_filial"])
                if pd.notna(row["matriz_filial"])
                else None
            ),
            registration_status=str(
                row["situacao_cadastral"]
            ),
            removed_from_mosc=(
                bool(row["removida_do_mosc"])
                if pd.notna(row["removida_do_mosc"])
                else None
            ),
            foundation_date=(
                row["dt_fundacao_osc"]
                if pd.notna(row["dt_fundacao_osc"])
                else None
            ),
            closing_date=(
                row["data_fechamento"]
                if pd.notna(row["data_fechamento"])
                else None
            ),
            closing_year=(
                int(row["ano_fechamento"])
                if pd.notna(row["ano_fechamento"])
                else None
            ),
            address=(
                str(row["tx_endereco_completo"])
                if pd.notna(row["tx_endereco_completo"])
                else None
            ),
            municipality_code=(
                int(row["cd_municipio"])
                if pd.notna(row["cd_municipio"])
                else None
            ),
            latitude=(
                float(row["latitude"])
                if pd.notna(row["latitude"])
                else None
            ),
            longitude=(
                float(row["longitude"])
                if pd.notna(row["longitude"])
                else None
            ),
        )

        session.add(organization)


def _load_organization_cnaes(
    df: pd.DataFrame,
    session: Session,
) -> None:
    """
    Loads organization/CNAE relationships.
    """

    organizations = {
        organization.cnpj: organization.id
        for organization in session.scalars(
            select(Organization)
        ).all()
    }

    existing_relationships = {
        (
            relationship.organization_id,
            relationship.cnae_code,
        )
        for relationship in session.scalars(
            select(OrganizationCnae)
        ).all()
    }

    for _, row in df.iterrows():
        organization_id = organizations.get(
            str(row["cnpj"])
        )

        if organization_id is None:
            continue

        cnae_codes: list[tuple[str, bool]] = []

        if pd.notna(row["cnae"]):
            cnae_codes.append(
                (
                    str(row["cnae"]).strip(),
                    True,
                )
            )

        if pd.notna(row["cnae_secundaria"]):
            for code in str(
                row["cnae_secundaria"]
            ).split("|"):
                code = code.strip()

                if code:
                    cnae_codes.append(
                        (
                            code,
                            False,
                        )
                    )

        for code, is_primary in cnae_codes:
            key = (
                organization_id,
                code,
            )

            if key in existing_relationships:
                continue

            session.add(
                OrganizationCnae(
                    organization_id=organization_id,
                    cnae_code=code,
                    is_primary=is_primary,
                )
            )

            existing_relationships.add(key)


def _load_organization_areas(
    df: pd.DataFrame,
    session: Session,
) -> None:
    """
    Loads organization/activity-area relationships.
    """

    organizations = {
        organization.cnpj: organization.id
        for organization in session.scalars(
            select(Organization)
        ).all()
    }

    areas = {
        area.name: area.id
        for area in session.scalars(
            select(ActivityArea)
        ).all()
    }

    existing_relationships = {
        (
            relationship.organization_id,
            relationship.area_id,
        )
        for relationship in session.scalars(
            select(OrganizationArea)
        ).all()
    }

    for _, row in df.iterrows():
        organization_id = organizations.get(
            str(row["cnpj"])
        )

        if organization_id is None:
            continue

        for column, area_name in AREA_COLUMNS.items():
            if pd.isna(row[column]):
                continue

            if row[column] != 1:
                continue

            area_id = areas[area_name]

            key = (
                organization_id,
                area_id,
            )

            if key in existing_relationships:
                continue

            session.add(
                OrganizationArea(
                    organization_id=organization_id,
                    area_id=area_id,
                )
            )

            existing_relationships.add(key)


def _load_organization_subareas(
    df: pd.DataFrame,
    session: Session,
) -> None:
    """
    Loads organization/activity-subarea relationships.
    """

    organizations = {
        organization.cnpj: organization.id
        for organization in session.scalars(
            select(Organization)
        ).all()
    }

    areas = {
        area.name: area.id
        for area in session.scalars(
            select(ActivityArea)
        ).all()
    }

    subareas = {
        (subarea.area_id, subarea.name): subarea.id
        for subarea in session.scalars(
            select(ActivitySubarea)
        ).all()
    }

    existing_relationships = {
        (
            relationship.organization_id,
            relationship.subarea_id,
        )
        for relationship in session.scalars(
            select(OrganizationSubarea)
        ).all()
    }

    for _, row in df.iterrows():
        organization_id = organizations.get(
            str(row["cnpj"])
        )

        if organization_id is None:
            continue

        for column, (subarea_name, area_name) in (
            SUBAREA_COLUMNS.items()
        ):
            if pd.isna(row[column]):
                continue

            if row[column] != 1:
                continue

            area_id = areas[area_name]

            subarea_id = subareas.get(
                (
                    area_id,
                    subarea_name,
                )
            )

            if subarea_id is None:
                continue

            key = (
                organization_id,
                subarea_id,
            )

            if key in existing_relationships:
                continue

            session.add(
                OrganizationSubarea(
                    organization_id=organization_id,
                    subarea_id=subarea_id,
                )
            )

            existing_relationships.add(key)
